package com.paascloud.provider.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table example
 */
public class Example {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example.example_field_varchar
     *
     * @mbg.generated
     */
    private String exampleFieldVarchar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example.example_field_int
     *
     * @mbg.generated
     */
    private Integer exampleFieldInt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example.id
     *
     * @return the value of example.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example.id
     *
     * @param id the value for example.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example.example_field_varchar
     *
     * @return the value of example.example_field_varchar
     *
     * @mbg.generated
     */
    public String getExampleFieldVarchar() {
        return exampleFieldVarchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example.example_field_varchar
     *
     * @param exampleFieldVarchar the value for example.example_field_varchar
     *
     * @mbg.generated
     */
    public void setExampleFieldVarchar(String exampleFieldVarchar) {
        this.exampleFieldVarchar = exampleFieldVarchar == null ? null : exampleFieldVarchar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example.example_field_int
     *
     * @return the value of example.example_field_int
     *
     * @mbg.generated
     */
    public Integer getExampleFieldInt() {
        return exampleFieldInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example.example_field_int
     *
     * @param exampleFieldInt the value for example.example_field_int
     *
     * @mbg.generated
     */
    public void setExampleFieldInt(Integer exampleFieldInt) {
        this.exampleFieldInt = exampleFieldInt;
    }
}