package com.paascloud.provider.dao;

import com.paascloud.provider.domain.Example;

public interface ExampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated
     */
    int insert(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated
     */
    int insertSelective(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated
     */
    Example selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Example record);
}