spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: paascloud-provider-example
          uri: lb://paascloud-provider-example
          predicates:
            - Path=/example/**
          filters:
            - StripPrefix=1
  main:
    allow-bean-definition-overriding: true

